// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZac4ldkO4fQrSPi0l4MipYvtzZiouxI',
    appId: '1:600306167967:android:65f080082d2a16667732aa',
    messagingSenderId: '600306167967',
    projectId: 'easecortebaseversion1',
    storageBucket: 'easecortebaseversion1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3-xX3aRVjVNEtit_8sR7mDCwzupoKkBI',
    appId: '1:600306167967:ios:f813dbfdaf1bce8d7732aa',
    messagingSenderId: '600306167967',
    projectId: 'easecortebaseversion1',
    storageBucket: 'easecortebaseversion1.appspot.com',
    iosBundleId: 'com.easecorte.v1',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjlUdm9dG6kj6Gr_w7CRDcVeQHsFCBZ-k',
    appId: '1:600306167967:web:5c32d95e8f96370e7732aa',
    messagingSenderId: '600306167967',
    projectId: 'easecortebaseversion1',
    authDomain: 'easecortebaseversion1.firebaseapp.com',
    storageBucket: 'easecortebaseversion1.appspot.com',
    measurementId: 'G-WYZWYQKB2W',
  );

}